modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/SquidNoGlitch/issues"

[[mods]]
modId = "squidnoglitch"
version = "${version}"
displayName = "Squid No Glitch"
description = "A tiny mod that fixes various vanilla bugs with the squid"
displayURL = "https://modrinth.com/mod/squid-no-glitch"
logoFile = "logo.png"
authors = "SteveKunG"

[[dependencies.squidnoglitch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"