modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/SteveKunG/SquidNoGlitch/issues"

[[mods]]
modId = "squidnoglitch"
version = "${version}"
displayName = "Squid No Glitch"
description = "A tiny mod that fixes various vanilla bugs with the squid"
displayURL = "https://modrinth.com/mod/squid-no-glitch"
logoFile = "logo.png"
authors = "SteveKunG"

[[mixins]]
config = "mixins.squidnoglitch.json"

[[dependencies.squidnoglitch]]
modId = "minecraft"
type = "required"
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"